<<<<<<< HEAD
=======
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

>>>>>>> d2525a3ee239d7281b3d8781e34e9a6214099d6a
trigger:
- '*'

pool:
<<<<<<< HEAD
  vmImage: 'ubuntu-16.04'
  demands:
    - npm

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '2.1.505'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'
=======
  vmImage: 'ubuntu-18.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.300'
  inputs:
    packageType: sdk
    version: 3.1.300
>>>>>>> d2525a3ee239d7281b3d8781e34e9a6214099d6a

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

<<<<<<< HEAD
- script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
=======
- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
>>>>>>> d2525a3ee239d7281b3d8781e34e9a6214099d6a
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
<<<<<<< HEAD
  workingDirectory: $(wwwrootDir)
=======
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot
>>>>>>> d2525a3ee239d7281b3d8781e34e9a6214099d6a

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

<<<<<<< HEAD
- template: templates/build.yml
  parameters:
    buildConfiguration: 'Debug'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()
=======
- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'

>>>>>>> d2525a3ee239d7281b3d8781e34e9a6214099d6a
